---
# file: roles/haproxy/tasks/firewall.yml
# TODO: [DEPRECATION WARNING]: The firewalld module has been moved to the ansible.posix
#       collection. This feature will be removed from community.general in version
#       2.0.0.
- name: HAproxy firewalld rule
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ haproxy_fw_ports }}"
