---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -ex
  yamllint -s .
  ansible-lint --nocolor -p --parseable-severity --exclude=molecule/ --exclude=tests/
  flake8
platforms:
  # https://wiki.debian.org/DebianReleases
  - name: debian10
    image: debian:10-slim
    command: sleep infinity
    groups: [ Debian ]
    privileged: true
  - name: debian9
    image: debian:9
    command: sleep infinity
    groups: [ Debian ]
    privileged: true
  # https://www.centos.org/centos-linux/
  - name: centos8
    image: centos:8
    command: /sbin/init
    groups: [ RedHat ]
    privileged: true
  - name: centos7
    image: centos:7
    command: /sbin/init
    groups: [ RedHat ]
    privileged: true
  # https://fedoraproject.org/wiki/Releases
  - name: f33
    image: fedora:33
    command: /sbin/init
    groups: [ RedHat ]
    privileged: true
  - name: f32
    image: fedora:32
    command: /sbin/init
    groups: [ RedHat ]
    privileged: true
  # https://wiki.ubuntu.com/Releases
  - name: ubuntu20.04
    image: ubuntu:20.04
    command: sleep infinity
    groups: [ Debian ]
    privileged: true
  - name: ubuntu18.04
    image: ubuntu:18.04
    command: sleep infinity
    groups: [ Debian ]
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      Debian:
        apache_pkg: apache2
        apache_service: apache2
        apache_ports: /etc/apache2/ports.conf
        apache_conf_d: /etc/apache2/conf-enabled
      RedHat:
        apache_pkg: httpd
        apache_service: httpd
        apache_ports: /etc/httpd/conf/httpd.conf
        apache_conf_d: /etc/httpd/conf.d
    host_vars:
      f33:
        ansible_python_interpreter: python3
      f32:
        ansible_python_interpreter: python3
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    v: true
